config/routes.rb
Rails.application.routes.draw do
  resources :phones
  
  root to: "phones#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:phone).permit(:make, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/layouts/_footer.html.erb
  <footer class="page-footer font-small blue pt-4 mt-4">

    <!--Footer Links-->
    <div class="container-fluid text-center text-md-left">
        <div class="row">

            <!--First column-->
            <div class="col-md-6">
                <h5 class="text-uppercase">Remember to follow us!</h5>
                <p><a class="btn-floating btn-sm btn-tw mx-1" href="https://twitter.com"><i> Twitter </i></a></p>
                <p><a class="btn-floating btn-sm btn-fb mx-1" href="https://www.facebook.com"><i>Facebook</i></a></p>
                <p><a class="btn-floating btn-sm btn-gplus mx-1" href="https://www.instagram.com"><i>Instagram</i></a></p>
            </div>
            <!--/.First column-->
            
            <!--Second column-->
            <div class="col-md-6">
                <h5 class="text-uppercase">Popular Models</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="#!">Apple</a>
                    </li>
                    <li>
                        <a href="#!">Samsung</a>
                    </li>
                    <li>
                        <a href="#!">Nokia</a>
                    </li>
                    <li>
                        <a href="#!">Huawei</a>
                    </li>
                </ul>
            </div>
            <!--/.Second column-->
        </div>
    </div>
    
                       <div class="text-center py-3">
        <ul class="list-unstyled list-inline mb-0">
            <li class="list-inline-item">
                <a href="#!" class="btn btn-danger btn-rounded" onclick="doClick()">Click Me</a>
            </li>
        </ul>
    </div>
    <!--/.Footer Links-->

         <hr class="clearfix d-md-none rgba-white-light" style="margin: 0.5% 4% 1%;">

    
    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
        © 2018 Copyright:
        <a href="#"> PHONEWEBSITECA2.com </a>
    </div>
    <!--/.Copyright-->

</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-default" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <div id="logo" class="navbar-brand"><%= link_to "SHADECLOTHING", root_path %></div>
          <nav class="collapse navbar-collapse navbar-ex1-collapse">
    
   
          <ul class="nav navbar-nav navbar-right">    
                <li><%= link_to 'Submit Phone', new_phone_path %></li>
                <li><%= link_to 'Home', new_phone_path %></li>
                <li><%= link_to 'Products', new_phone_path %></li>
          </ul>
        </nav>
      </div>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhonesiteCA</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
   
    
    <div class="center jumbotron">
       <div id="container">
            <h1>Welcome to the store</h1>
            <div class="jackpots">SHADE</div>
          </div>
      </div>
    
    <div id="main_content" class="container">
      
      <div id="content" class="col-md-9 center-block">
        <%= yield %>
        
      </div>
    </div>
    
    
    <div class="container button">
       <button type="button" class="btn btn-primary" onmouseout="clearDate()" onmouseover="showDate()">Show Date</button>
          <h3 id="time"></h3>
    </div>
  
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/phones/_form.html.erb
<%= form_with(model: phone, local: true) do |form| %>
  <% if phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= form.label :make %><br>
    <%= form.text_field :make, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price %><br>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>


  

app/views/phones/edit.html.erb
<h1>Editing Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<% @phones.each do |phone| %>


  <div class="link row clearfix">
    <h2>
      <%= link_to phone.make, phone %><br>
      <small class="author">Submitted <%= time_ago_in_words(phone.created_at) %> ago</small>
      
    </h2>
  </div>
<% end %>

app/views/phones/new.html.erb
<h1>New Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<div class="page-header">
  <h1><a href="#"><%= @phone.make %></a><br> <small>You deserve this phone</small></h1>
  <p>
  <strong>Price:</strong>
  <%= @phone.price %>
</p>
</div>

<div class="btn-group">
	<%= link_to 'Back', root_path, class: "btn btn-primary" %>
</div>

	<div class="btn-group">
		<%= link_to 'Edit', edit_phone_path(@phone), class: "btn btn-default" %>
		<%= link_to 'Destroy', @phone, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>